name: dibbs
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  # Flutter
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.0
  google_sign_in: ^5.0.0
  shared_preferences: ^2.0.3
  image_picker: ^0.7.2

  # Dart
  intl: ^0.17.0
  intl_translation: ^0.17.10+1

  # Firebase
  firebase_core: ^1.0.0
  cloud_firestore: ^1.0.0
  firebase_auth: ^1.0.0
  firebase_storage: ^8.0.0

  # Third party
  auth_buttons: ^1.0.0
  smooth_page_indicator: ^0.2.1
  tap_debouncer: ^1.0.1
  pinput: ^1.1.0
  enum_to_string: ^1.0.14
  equatable: ^2.0.0
  reorderables: ^0.3.2
  paginate_firestore: ^0.3.1
  timeago: ^3.0.2

  # Debugging
  logger: ^0.9.4

  # Testing
  # cloud_firestore_mocks: ^0.6.0

dependency_overrides:
    intl: "0.17.0"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/ad-placeholder.png

  fonts:
  - family: SF-Pro-Text
    fonts:
      - asset: assets/fonts/SF-Pro-Text-Bold.otf
        weight: 700
      - asset: assets/fonts/SF-Pro-Text-BoldItalic.otf
        weight: 700
        style: italic
      - asset: assets/fonts/SF-Pro-Text-Medium.otf
      - asset: assets/fonts/SF-Pro-Text-MediumItalic.otf
        style: italic
  - family: SF-Pro-Display
    fonts:
      - asset: assets/fonts/SF-Pro-Display-Bold.otf
        weight: 700
      - asset: assets/fonts/SF-Pro-Display-BoldItalic.otf
        weight: 700
        style: italic
      - asset: assets/fonts/SF-Pro-Display-Medium.otf
      - asset: assets/fonts/SF-Pro-Display-MediumItalic.otf
        style: italic