name: dibbs
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  # Flutter
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.0
  google_sign_in: ^4.5.6
  shared_preferences: ^0.5.12+4

  # Dart
  intl: ^0.16.1
  intl_translation: ^0.17.10+1

  # Firebase
  firebase_core: ^0.5.2
  cloud_firestore: ^0.14.3
  firebase_auth: ^0.18.3
  firebase_storage: ^5.0.1

  # Third party
  auth_buttons: ^0.0.4
  smooth_page_indicator: ^0.2.0
  tap_debouncer: ^1.0.1
  pinput: ^0.2.0
  enum_to_string: ^1.0.14
  equatable: ^1.2.5

  # Debugging
  logger: ^0.9.4

  # Testing
  cloud_firestore_mocks: ^0.5.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true