name: dibbs
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  # Flutter
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.0
  google_sign_in: ^4.5.6
  shared_preferences: ^0.5.12+4
  image_picker: ^0.6.7+15

  # Dart
  intl: ^0.16.1
  intl_translation: ^0.17.10+1

  # Firebase
  firebase_core: ^0.7.0
  cloud_firestore: ^0.16.0+1
  firebase_auth: ^0.20.1
  firebase_storage: ^7.0.0

  # Third party
  auth_buttons: ^0.0.4
  smooth_page_indicator: ^0.2.1
  tap_debouncer: ^1.0.1
  pinput: ^0.2.0
  enum_to_string: ^1.0.14
  equatable: ^1.2.5
  reorderables: ^0.3.2
  paginate_firestore: ^0.3.0+1

  # Debugging
  logger: ^0.9.4

  # Testing
  # cloud_firestore_mocks: ^0.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/ad-placeholder.png

  fonts:
  - family: SF-Pro-Text
    fonts:
      - asset: assets/fonts/SF-Pro-Text-Bold.otf
        weight: 700
      - asset: assets/fonts/SF-Pro-Text-BoldItalic.otf
        weight: 700
        style: italic
      - asset: assets/fonts/SF-Pro-Text-Medium.otf
      - asset: assets/fonts/SF-Pro-Text-MediumItalic.otf
        style: italic
  - family: SF-Pro-Display
    fonts:
      - asset: assets/fonts/SF-Pro-Display-Bold.otf
        weight: 700
      - asset: assets/fonts/SF-Pro-Display-BoldItalic.otf
        weight: 700
        style: italic
      - asset: assets/fonts/SF-Pro-Display-Medium.otf
      - asset: assets/fonts/SF-Pro-Display-MediumItalic.otf
        style: italic